export type Platform = {
  id: number;
  name: string;
};

export const platforms: Platform[] = [
  { id: 1, name: 'Amiga' },
  { id: 3, name: 'Game Boy' },
  { id: 4, name: 'Game Boy Advance' },
  { id: 5, name: 'Game Gear' },
  { id: 6, name: 'Genesis' },
  { id: 7, name: 'Atari Lynx' },
  { id: 8, name: 'Sega Master System' },
  { id: 9, name: 'Super Nintendo Entertainment System' },
  { id: 11, name: 'Amstrad CPC' },
  { id: 12, name: 'Apple II' },
  { id: 13, name: 'Atari ST' },
  { id: 14, name: 'Commodore 64' },
  { id: 15, name: 'MSX' },
  { id: 16, name: 'ZX Spectrum' },
  { id: 17, name: 'Mac' },
  { id: 18, name: 'PlayStation Portable' },
  { id: 19, name: 'PlayStation 2' },
  { id: 20, name: 'Xbox 360' },
  { id: 21, name: 'Nintendo Entertainment System' },
  { id: 22, name: 'PlayStation' },
  { id: 23, name: 'GameCube' },
  { id: 24, name: 'Atari 8-bit' },
  { id: 25, name: 'Neo Geo' },
  { id: 26, name: '3DO' },
  { id: 27, name: 'CD-i' },
  { id: 28, name: 'Jaguar' },
  { id: 29, name: 'Sega CD' },
  { id: 30, name: 'VIC-20' },
  { id: 31, name: 'Sega 32X' },
  { id: 32, name: 'Xbox' },
  { id: 34, name: 'N-Gage' },
  { id: 35, name: 'PlayStation 3' },
  { id: 36, name: 'Wii' },
  { id: 37, name: 'Dreamcast' },
  { id: 38, name: 'Apple IIgs' },
  { id: 39, name: 'Amiga CD32' },
  { id: 40, name: 'Atari 2600' },
  { id: 42, name: 'Saturn' },
  { id: 43, name: 'Nintendo 64' },
  { id: 47, name: 'ColecoVision' },
  { id: 48, name: 'TI-99/4A' },
  { id: 51, name: 'Intellivision' },
  { id: 52, name: 'Nintendo DS' },
  { id: 53, name: 'TurboGrafx-CD' },
  { id: 54, name: 'WonderSwan Color' },
  { id: 55, name: 'TurboGrafx-16' },
  { id: 57, name: 'Game Boy Color' },
  { id: 58, name: 'Commodore 128' },
  { id: 59, name: 'Neo Geo CD' },
  { id: 60, name: 'Odyssey 2' },
  { id: 61, name: 'Dragon 32/64' },
  { id: 62, name: 'Commodore PET/CBM' },
  { id: 63, name: 'TRS-80' },
  { id: 64, name: 'Zodiac' },
  { id: 65, name: 'WonderSwan' },
  { id: 66, name: 'Channel F' },
  { id: 67, name: 'Atari 5200' },
  { id: 68, name: 'TRS-80 CoCo' },
  { id: 70, name: 'Atari 7800' },
  { id: 72, name: 'iPod' },
  { id: 74, name: 'Odyssey' },
  { id: 75, name: 'PC-FX' },
  { id: 76, name: 'Vectrex' },
  { id: 77, name: 'Game.Com' },
  { id: 78, name: 'Gizmondo' },
  { id: 79, name: 'Virtual Boy' },
  { id: 80, name: 'Neo Geo Pocket' },
  { id: 81, name: 'Neo Geo Pocket Color' },
  { id: 82, name: 'V.Smile' },
  { id: 83, name: 'Pinball' },
  { id: 84, name: 'Arcade' },
  { id: 85, name: 'NUON' },
  { id: 86, name: 'Xbox 360 Games Store' },
  { id: 87, name: 'Wii Shop' },
  { id: 88, name: 'PlayStation Network (PS3)' },
  { id: 89, name: 'Leapster' },
  { id: 90, name: 'Microvision' },
  { id: 91, name: 'Famicom Disk System' },
  { id: 92, name: 'Pioneer LaserActive' },
  { id: 93, name: 'Adventure Vision' },
  { id: 94, name: 'PC' },
  { id: 95, name: 'Sharp X68000' },
  { id: 96, name: 'iPhone' },
  { id: 98, name: 'Satellaview' },
  { id: 99, name: 'Arcadia 2001' },
  { id: 100, name: 'Aquarius' },
  { id: 101, name: 'Nintendo 64DD' },
  { id: 102, name: 'Pippin' },
  { id: 103, name: 'R-Zone' },
  { id: 104, name: 'HyperScan' },
  { id: 105, name: 'Game Wave' },
  { id: 106, name: 'DSiWare' },
  { id: 107, name: 'RDI Halcyon' },
  { id: 108, name: 'FM Towns' },
  { id: 109, name: 'NEC PC-8801' },
  { id: 110, name: 'BBC Micro' },
  { id: 111, name: 'PLATO' },
  { id: 112, name: 'NEC PC-9801' },
  { id: 113, name: 'Sharp X1' },
  { id: 114, name: 'FM-7' },
];
